### ISSUE TITLE
Data Sets saving

### ISSUE THREAD

**Issue by Juebo** [Qalculate/qalculate-gtk#213]
Saving of Data Sets does not work.

I use "Manage Data Sets", select an own data set which already contains data and add a new data object.
On the first view this looks ok, but after saving all the old data objects are lost.

**Comment by hanna-kn** [comment]
Now fixed in libqalculate.

I've never used the data set editing functionality, in the GUI, myself and it probably needs a lot more testing to become reliable.

**Comment by Juebo** [comment]
Hello Hanna
Thank you. I will test this with the next release.

Yes, editing with Vim works :-)

Kind Regards

**Comment by Juebo** [comment]
Hello Hanna
Thank you. I will test this with the next release.

Yes, editing with Vim works :-)

Kind Regards

**Comment by Juebo** [comment]
Hello Hanna,
in 3.16.0 this still doesn't work
Now I can add some data objects to a data set, but I got the feeling that the whole data file has been deleted from time to time. I can not really reproduce, when this happens. But when you hit "File/Save Definitions" the data file is definitely deleted.
Kind Regards

**Comment by hanna-kn** [comment]
It should be fixed now. I apologize for my inadequate testing.

**Comment by hanna-kn** [comment]
I realized that the bug in version 3.16.0 is much worse than the original issue and I've therefore quickly released a new version of the libqalculate (3.16.1).

**Comment by Juebo** [comment]
Hello Hanna,
now it seems to work. Thank you.
